fileConfigs:
  04_outputs.conf: |-
    <label @OUTPUT>
      <match **>
        @type elasticsearch
        host "elasticsearch-master"
        port 9200
        path ""
        index_name fluentd
      </match>
    </label>


dashboards:
  enabled: "false"

env:
- name: "FLUENTD_CONF"
  value: "../../../etc/fluent/fluent.conf"
- name: FLUENT_ELASTICSEARCH_HOST
  value: "elasticsearch-master-headless.default.svc.cluster.local"
- name: FLUENT_ELASTICSEARCH_PORT
  value: "9200"
- name: FLUENT_ELASTICSEARCH_SCHEME
  value: "http"
- name: FLUENTD_SYSTEMD_CONF
  value: disable