fileConfigs:
  04_outputs.conf: |-
    <label @OUTPUT>
      <match **>
        @type elasticsearch
        host "elasticsearch-master"
        port 9200
        path ""
        index_name fluentd
      </match>
    </label>


dashboards:
  enabled: "false"