apiversion: v1
kind: pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
    -name: livenss
     image: public.ecr.aws/t0g1s4n9/testsimplewebserver:1.1
     livenessProbe:
       httpGet:
         path: /healthz
         port: 8080
       initalDealtSecounds: 3
       periosSecounds: 3