apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-server
  labels:
    app: simple-web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-web-server
  template:
    metadata:
      labels:
        app: simple-web-server
    spec:
      containers:
        - name: simple-web-server
          image: simple-web-server:0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-server-service
spec:
  selector:
    app: simple-web-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080