apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-server
  labels:
    app: simple-web-server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: simple-web-server
  template:
    metadata:
      labels:
        app: simple-web-server
    spec:
      containers:
        - name: simple-web-server
          image: 955114013936.dkr.ecr.us-east-2.amazonaws.com/simplewebapp:1.1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          initiaalDelayDecounds: 3
          periodSecounds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-server-service
spec:
  type: NodePort
  selector:
    app: simple-web-server
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30100